import csv
import re

import requests
import json
import time

apikeys = ["KEY1","KEY2"]



def detect_ai_text(textos, write):
    api_key = apikeys[0]
    posicaoKEY = 0
    api_url = "https://api.deepinfra.com/v1/openai/chat/completions"

    with open(write, mode="w", newline="", encoding="utf-8") as arquivo:
        fd = csv.writer(arquivo, delimiter="\t")
        fd.writerow(['ID', 'Label'])

        i:int = 1

        fdRead = open(textos, mode='r', encoding='utf-8')
        headerRead = fdRead.readline()
        reader = csv.reader(fdRead, delimiter="\t")

        for texto in reader:

            headers = {
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            }

            texts = f"""
            Analyze the following text and determine if it was likely written by a human or an AI. 
            You will only answer AI if you think the text was generated by an AI or Human if it was written by a human.
            Below I leave 5 examples, the field before the ; identifies whether the text is generated by Ia or written by a person, the field after the ; is the text
            Example text:
            AI; Obesity is recognized as a major risk factor for type 2 diabetes, though it does not directly cause the disease. The connection between these conditions is so significant that healthcare professionals have coined the term diabesity to highlight that the majority of individuals with diabetes are obese or overweight demonstrates that the risk of developing type 2 diabetes increases linearly with rising body mass index. This explains why the worldwide increase in obesity prevalence has led to a corresponding surge in type 2 diabetes cases globally. The relationship works through several mechanisms: excess body fat, particularly visceral fat, affects insulin sensitivity and function. Some individuals with obesity can produce more insulin without overtaxing the pancreasy.
            Human;The cell cycle, or cell-division cycle, is the sequential series of events that take place in a cell that causes it to divide into two daughter cells. These events include the growth of the cell, duplication of its DNA (DNA replication) and some of its organelles, and subsequently the partitioning of its cytoplasm, chromosomes and other components into two daughter cells in a process called cell division. In eukaryotic cells (having a cell nucleus) including animal, plant, fungal, and protist cells, the cell cycle is divided into two main stages: interphase, and the M phase that includes mitosis and cytokinesis.
            AI;A photon is a fundamental particle of light and other electromagnetic radiation. It has no mass, no electric charge, and always moves at the speed of light (299,792,458 m/s in a vacuum). Photons carry energy and momentum, which depend on their wavelength or frequency. Higher frequency photons (like X-rays) have more energy, while lower frequency photons (like radio waves) have less. Their energy is given by Planck’s equation:E = h f, where E is energy, h is Planck’s constant, and f is frequency.Photons behave as both particles and waves (wave-particle duality), meaning they can interfere, diffract, and be absorbed/emitted like particles. They are responsible for vision, photosynthesis, solar power, and many quantum phenomena.
            Human;Photons, in many atomic models in physics, are particles which transmit light. In other words, light is carried over space by photons. Photon is an elementary particle that is its own antiparticle. In quantum mechanics each photon has a characteristic quantum of energy that depends on frequency: A photon associated with light at a higher frequency will have more energy (and be associated with light at a shorter wavelength).Photons have a rest mass of 0 (zero). However, Einstein's theory of relativity says that they do have a certain amount of momentum. Before the photon got its name, Einstein revived the proposal that light is separate pieces of energy (particles). These particles came to be known as photons.
            AI;"The question of how life appeared on Earth is one of science’s greatest mysteries. While there is no definitive answer, scientists propose various theories based on evidence and hypotheses.VPrimordial Soup Theory: This idea suggests that life began in a ""soup"" of organic molecules in early Earth's oceans. Energy from lightning, volcanic activity, or UV radiation may have triggered chemical reactions, forming basic building blocks of life like amino acids and nucleotides. Experiments like the 1953 Miller-Urey experiment support this theory by showing that organic molecules can form under simulated early Earth conditions. Hydrothermal Vent Hypothesis: Some researchers believe life began near deep-sea hydrothermal vents, where hot, mineral-rich water provided the energy and raw materials for life."
            Human;"We investigate the problem about the reason for the significant sub-centurial (50-55 and 60-65 yr) and quasi-centurial (120-130 yr) climatic oscillations. The 50-55 and 60-65 yr cycles are clearly detectable in numerous global and regional climatic parameters, i.e. in the temperatures of the Northern Hemisphere and World Ocean surface, in the tree rings widths, in the atmosphere concentration of CO2, etc. Searching for analogues of these cycles in the solar activity we study the connections between various types of solar, geophysical and climatic cycles. In this Paper I we analyze time series of residual variations of the Northern Hemisphere (AD 1610-1979) and World Ocean surface (AD 18561995) temperatures in respect to the corresponding regression models ""sunspot activity – temperature""."  
            
            Now you can only answer AI or Human. Text to be evaluated: {texto[1]}"""
            prompt= texts

            data = {
                "model": "mistralai/Mistral-7B-Instruct-v0.1",
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.3
            }

            response = requests.post(api_url, headers=headers, data=json.dumps(data))

            if response.status_code == 200:
                if re.findall("human", response.json()["choices"][0]["message"]["content"],re.I):
                    fd.writerow([texto[0],"Human"])

                elif re.findall("ai", response.json()["choices"][0]["message"]["content"],re.I):
                    fd.writerow([texto[0],"AI"])

                else:
                    print(f"Regex MAU :( {response.json()['choices'][0]['message']['content']}")

                print(f"Escrevi {i}")
                i+=1

            else:

                print(f"Erro na requisição {i}: {response.status_code} - {response.text}")
                if response.status_code == 402:
                    if posicaoKEY < len(apikeys):
                        posicaoKEY += 1
                        api_key = apikeys[posicaoKEY]

                    else:
                        print("No more keys available")
                        exit(-1)

                else:
                    print("ERRO ESTRANHO")
                    exit(0)

                headers = {
                    "Authorization": f"Bearer {api_key}",
                    "Content-Type": "application/json",
                }

                response = requests.post(api_url, headers=headers, data=json.dumps(data))

                while response.status_code != 200:
                   time.sleep(10)
                   response = requests.post(api_url, headers=headers, data=json.dumps(data))

                fd.writerow([f"D1-{i}", f"{response.json()["choices"][0]["message"]["content"]}"])
                print(f"Escrevi {i}")
                i += 1


        arquivo.close()
detect_ai_text("dataset1_inputs.csv", "respIA.csv")


fdReadHuman = open("respIA.csv", mode='r', encoding='utf-8')

headerReadHuman = fdReadHuman.readline()
snifferHuman = csv.Sniffer()
delimiterDataset = snifferHuman.sniff(headerReadHuman).delimiter
readerHumanCSV = csv.reader(fdReadHuman, delimiter=delimiterDataset)

fdReadIA = open("dataset1_outputs.csv", mode='r', encoding='utf-8')
headerReadIA = fdReadIA.readline()
snifferIA = csv.Sniffer()
delimiterDataset = snifferIA.sniff(headerReadIA).delimiter
readerIACSV = csv.reader(fdReadIA, delimiter=delimiterDataset)

numero = 0
numeroAcerto = 0

for rowIA, rowHuman in zip(readerIACSV, readerHumanCSV):

    if rowHuman[1] == rowIA[1]:
        numeroAcerto+=1
    numero+=1

perAcertos =numeroAcerto/numero * 100

print(f"Percentagem: {perAcertos}")

